{% set name = "duet" %}
{% set version = "0.2.9" %}


package:
  name: {{ name|lower }}-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6fa39582e6a3dce1096c47e5fbcbda648a633eed94a38943e68662afa2587f3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - typing_extensions >=3.10.0

test:
  imports:
    - duet
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/google/duet
  summary: A simple future-based async library for python.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
